name: Run Brails++ tests

on: push
  # workflow_dispatch:
  # schedule:
  #   - cron: "0 5 * * *"

jobs:
  setup_and_test:
    name: Setup and run tests
    runs-on: ubuntu-latest
    # environment: quoFEM
    env:  
      API_KEY: ${{ secrets.API_KEY }}
      ONPENAI_KEY: ${{ secrets.OPENAI_KEY }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - run: echo $API_KEY > ./examples/api_key.txt
      - run: echo $OPENAI_KEY > ./examples/chatGPT_key.txt
      - run: python -m pip install git+https://github.com/NHERI-SimCenter/BrailsPlusPlus
      - run: sudo apt-get update
      - run: sudo apt-get install freeglut3-dev -y
      - run: source ./runTest.sh
